src/index/routes.py
"""Routes module of 'index' package."""

from __future__ import annotations

from flask import Blueprint # type: ignore
from flask import render_template, request # type: ignore
from src.database import session_var
from src.users.models import User, UserSession


bp = Blueprint("index", __name__, template_folder="templates")


@bp.route("/")
@bp.route("/index")
def index() -> str:
    """Handle index page."""
    session = session_var.get()

    # Verificar si la cookie de la sesión está presente
    session_id = request.cookies.get('session_id')
    if session_id:
        user_session = session.query(UserSession).filter_by(session_id=session_id).first()
        if user_session:
            # El usuario está autenticado, obtenemos el objeto `User`
            current_user = session.query(User).filter_by(id=user_session.user_id).first()
        else:
            current_user = None
    else:
        current_user = None

    users = session.query(User).all()
    active_sessions = session.query(UserSession).all()
    active_user_ids = {user_session.user_id for user_session in active_sessions}
    print(f"usuario recuperado: {current_user}")

    
    # Pasar user_id al template para determinar si el usuario está autenticado
    return render_template("index.html", users=users, active_user_ids=active_user_ids, current_user=current_user)

src/users/routes.py
"""Routes module of 'users' package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flask import Blueprint, flash
from flask import make_response, redirect, render_template, request, url_for

from src.users.forms import LoginForm, RegistrationForm
from src.users.models import User, UserSession
from src.database import session_var

if TYPE_CHECKING:
    from werkzeug.wrappers.response import Response


bp = Blueprint("users", __name__, template_folder="templates")

def is_user_active(user_id):
    session = session_var.get()
    active_session = session.query(UserSession).filter_by(user_id=user_id).first()
    if active_session:
        return True
    return False

@bp.route("/registration", methods=["POST", "GET"])
def registration() -> str | Response:
    """Handle user's registration form."""
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.get_user_by_username(form.username.data)
        if user:
            flash("El usuario ya existe")
            return redirect(url_for("users.login"))
        User.create_user(form.username.data, form.password.data, form.role.data)
        return redirect(url_for("users.login"))
    return render_template("registration.html", form=form)


@bp.route("/login", methods=["POST", "GET"])
def login() -> str | Response:
    """Handle user's login form."""
    form = LoginForm()
    if form.validate_on_submit() and (user := User.get_user_by_credentials(form.username.data, form.password.data)):
        user_session = user.create_session()

        if user.role=="teacher":
            response = make_response(redirect(url_for("ia.dashboard_teacher")))
        else:
            response = make_response(redirect(url_for("topics.topics")))
        response.set_cookie("session_id", user_session.session_id, max_age=60*60*24, path='/')
        return response
    return render_template("login.html", form=form)


@bp.route("/logout")
def logout() -> Response:
    """Log out users."""
    session_id = request.cookies.get("session_id")
    session_to_delete = None
    print(f"Attempting to logout session: {session_id}")
    if session_id is not None:
        session_to_delete = UserSession.get_user_session_by_session_id(session_id)
        print(f"Session to delete: {session_to_delete}")
    if session_to_delete:
        session_to_delete.delete()
        print("session deteled")
    else:
        print("No session found to delete")
    response = make_response(redirect(url_for("users.login")))
    response.set_cookie("session_id", '', expires=0)  # Limpiar la cookie
    return response

src/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>forum.ia</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body class="bg-gray-100 text-gray-800 min-h-screen flex flex-col">
    <!-- Encabezado principal con imagen UOC y botones de navegación -->
    <div class="flex justify-between items-center p-4 bg-gray-700 text-white shadow-lg">
      
      <!-- Sección del logo y título del foro -->
      <div class="flex items-center">
        <img src="{{ url_for('static', filename='img/uoc.jpg') }}" alt="Logo UOC" class="h-20">
        <h1 class="ml-4 text-3xl font-bold tracking-wide leading-relaxed">Foro con IA</h1>
      </div>
      <!-- Mostrar nombre y rol del usuario autenticado solo si hay un usuario -->
      {% if current_user %}
        <div class="flex items-center space-x-4">
          <!-- Mostrar nombre del usuario autenticado -->
          <p class="flex items-center">
            <span>Conectado como: {{ current_user.username }}</span>            
          </p>
        </div>
      {% endif %}

      <!-- Botones de navegación (Inicio, Registro, Iniciar sesión) -->
      <div class="flex items-center space-x-4">
        
        <!-- Botón de inicio -->
        <a href="{{ url_for('index.index') }}" class="home-icon">
          <i class="fas fa-home text-white text-2xl transition duration-300 ease-in-out transform hover:scale-110"></i>
        </a>

        <!-- Icono de Pizarra para el acceso al Dashboard del Profesor -->
        {% if current_user and current_user.role == "teacher" %}
          <a href="{{ url_for('ia.dashboard_teacher') }}" class="mr-4">
            <i class="fas fa-chalkboard-teacher"></i>
          </a>
        {% endif %}

        <!-- Comprobación si el usuario está logueado -->
        {% if  current_user %}
        
        <!-- Botón de Cerrar Sesión -->
        <a href="{{ url_for('users.logout') }}" class="bg-red-500 hover:bg-red-600 px-4 py-2 rounded shadow-lg transition duration-300 ease-in-out transform hover:scale-110">
          Desconectar
        </a>
        <!-- Botón de acceder a Temas -->
        <a href="{{ url_for('topics.topics') }}" class="bg-purple-500 hover:bg-purple-600 px-4 py-2 rounded shadow-lg transition duration-300 ease-in-out transform hover:scale-110">
          Temas
        </a>

        {% else %}

        <!-- Botón de Registro -->
        <a href="{{ url_for('users.registration') }}" class="bg-green-500 hover:bg-green-600 px-4 py-2 rounded shadow-lg transition duration-300 ease-in-out transform hover:scale-110">
          Registro
        </a>

        <!-- Botón de Iniciar Sesión -->
        <a href="{{ url_for('users.login') }}" class="bg-blue-500 hover:bg-blue-600 px-4 py-2 rounded shadow-lg transition duration-300 ease-in-out transform hover:scale-110">
          Autentícate
        </a>

        {% endif %}
      </div>
    </div>
    
    <!-- Contenedor principal del contenido -->
    <div class="container mx-auto p-4 flex-grow">
      {% block content %}{% endblock %}
    </div>

    <!-- Footer del sitio -->
    <footer class="text-black p-4 text-center mt-8">
      <p>&copy; 2024 Foro con IA. Trabajo Fin de Grado: Angel Calvar Pastoriza.</p>
    </footer>

  </body>
</html>